permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

destination: _site
sass:
  sass_dir: _scss
  style: compressed

cover: /assets/images/default-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Choi Ji Hun
title: jihun's blog
description: "jihuns's blog"
keywords: "Jekyll"
url: https://cjh5414.github.io
baseurl: ""
domain_name: https://cjh5414.github.io
google_analytics: UA-52446115-1
repo: http://github.com/cjh5414
disqus_shortname: "nandothemes"

author:
  name      : Choi Ji Hun
  image     : /assets/images/author.jpg
  email     : cjh5414@gmail.com
  url       : cjh5414.github.io
  facebook  : http://facebook.com/profile.php?id=100003159672828
  twitter   : http://twitter.com/
  instagram : http://instagram.com/
  github    : http://github.com/cjh5414


exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
