# Site settings
title: jihun's blog
email: cjh5414@gmail.com
description: Um lindo tema feito para jekyll e com o <3
baseurl: ""
url: "https://cjh5414.github.io"

author:
  name     : 'Choi Ji Hun'
  email    : cjh5414@gmail.com
  url      : https://cjh5414.github.io
  facebook : https://www.facebook.com/profile.php?id=100003159672828
  twitter  : http://twitter.com/

github: https://github.com/cjh5414
disqus_shortname: "jihuns-development-blog"

google_analytics: UA-84670277-1

paginate: 6 # 6
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown : kramdown
permalink : /:title/
